# Churn Modeling Problem using Aritificial Neural Network

#### Part 1: Data Preprocessing

In [1]:
# import the Libraries
import numpy as np                   # used for multidimensional array
import pandas as pd                  # used for import the dataset
import matplotlib.pyplot as plt      # used for ploting the graph

In [2]:
# import the datset
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [9]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [3]:
X = dataset.iloc[: , 3:13].values             # independent variable
y = dataset.iloc[: , 13].values               # dependent variable

In [4]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [7]:
# Encoding the categorical data
from sklearn.preprocessing import LabelEncoder , OneHotEncoder
from sklearn.compose import ColumnTransformer

#Geography
labelencoder_X1 = LabelEncoder()
X[:, 1] = labelencoder_X1.fit_transform(X[ : , 1])

#Gender
labelencoder_X2 = LabelEncoder()
X[:, 2] = labelencoder_X2.fit_transform(X[: , 2])

#onehotencoder = OneHotEncoder(categorical_features = [1])
#X = onehotencoder.fit_transform(X).toarray()

columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [1])],     remainder='passthrough')
X=np.array(columnTransformer.fit_transform(X),dtype=np.str)
X = X[:, 1:]
X

array([['0.0', '0.0', '228', ..., '1', '1', '101348.88'],
       ['1.0', '0.0', '217', ..., '0', '1', '112542.58'],
       ['0.0', '0.0', '111', ..., '1', '0', '113931.57'],
       ...,
       ['0.0', '0.0', '318', ..., '0', '1', '42085.58'],
       ['0.0', '1.0', '381', ..., '1', '0', '92888.52'],
       ['0.0', '0.0', '401', ..., '1', '0', '38190.78']], dtype='<U32')

In [8]:
# split the dataset into test set and train set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(X,y, test_size= 0.2, random_state=0)

In [10]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
X_train

array([[ 1.74309049, -0.5698444 ,  0.1692298 , ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-0.57369368,  1.75486502, -2.30959   , ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.57369368, -0.5698444 , -1.19412109, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.57369368, -0.5698444 ,  0.90254733, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [ 1.74309049, -0.5698444 , -0.62605822, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-0.57369368,  1.75486502, -0.28522049, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [12]:
X_test

array([[-0.57369368,  1.75486502, -0.55375931, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [-0.57369368, -0.5698444 , -1.31806208, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [ 1.74309049, -0.5698444 ,  0.57203802, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [ 1.74309049, -0.5698444 , -0.74999921, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [-0.57369368,  1.75486502, -0.00635327, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [-0.57369368,  1.75486502, -0.80164129, ...,  0.64259497,
        -1.03227043,  1.61255917]])

#### Part 2: Let's make the ANN

In [13]:
# importing the Keras Libraries and package
import keras

In [14]:
from keras.models import Sequential   # used for init our ANN model

In [15]:
from keras.layers import Dense       # used for different layer structure

In [16]:
# initializing the ANN model
classifier = Sequential()

In [17]:
# adding the input layer and first hidden layer
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu',input_dim=11))

In [18]:
# adding the second hidden layer
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))

In [19]:
# adding the output layer
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

In [20]:
# compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [25]:
# fitting the ANN to the training set
classifier.fit(X_train, y_train, batch_size= 10, epochs= 20)

Epoch 1/20
800/800 [==============================] - 0s 521us/step - loss: 0.3631 - accuracy: 0.8520
Epoch 2/20
800/800 [==============================] - 0s 494us/step - loss: 0.3603 - accuracy: 0.8529
Epoch 3/20
800/800 [==============================] - 0s 494us/step - loss: 0.3586 - accuracy: 0.8522
Epoch 4/20
800/800 [==============================] - 0s 529us/step - loss: 0.3573 - accuracy: 0.8524
Epoch 5/20
800/800 [==============================] - 0s 535us/step - loss: 0.3561 - accuracy: 0.8555
Epoch 6/20
800/800 [==============================] - 0s 549us/step - loss: 0.3551 - accuracy: 0.8555
Epoch 7/20
800/800 [==============================] - 0s 535us/step - loss: 0.3536 - accuracy: 0.8561
Epoch 8/20
800/800 [==============================] - 0s 539us/step - loss: 0.3537 - accuracy: 0.8561
Epoch 9/20
800/800 [==============================] - 0s 504us/step - loss: 0.3528 - accuracy: 0.8568
Epoch 10/20
800/800 [==============================] - 0s 529us/step - loss: 0.351

#### Part 3: Making the Prediction and Accuracy Result

In [26]:
# predicting the test set result
y_pred = classifier.predict(X_test)
y_pred = (y_pred>0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [27]:
# Confusion Metric
from sklearn.metrics import confusion_matrix
confusion_metric = confusion_matrix(y_test, y_pred)
confusion_metric

array([[1574,   21],
       [ 266,  139]], dtype=int64)

In [28]:
# accuracy score
from sklearn.metrics import accuracy_score
accuracy_score = accuracy_score(y_test, y_pred)
accuracy_score

0.8565

#### Part 4 - Evaluating  the Artificial Neural Network

In [29]:
# Evaluating the ANN
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)

accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)

mean = accuracies.mean()
variance = accuracies.std()

In [30]:
mean = accuracies.mean()
variance = accuracies.std()
print(mean)
print(variance)
print(accuracies)

0.8298750042915344
0.008449300581311854
[0.82499999 0.83625001 0.82875001 0.82625002 0.85000002 0.83125001
 0.83249998 0.81875002 0.81999999 0.82999998]


#### Part 5: Improving and Tuning of ANN

In [34]:
# Dropout Regularization to reduce overfitting if needed
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier)

parameters = {'batch_size': [25, 32],
              'epochs': [10, 20],
              'optimizer': ['adam', 'rmsprop']}

# we use Grid_Searcf_CV to find the best parameters for the classifier.
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10)

grid_search = grid_search.fit(X_train, y_train)

best_parameters = grid_search.best_params_


Epoch 1/10
534/534 [==============================] - 0s 517us/step - loss: 0.5162 - accuracy: 0.7975
Epoch 2/10
534/534 [==============================] - 0s 514us/step - loss: 0.4315 - accuracy: 0.7980
Epoch 3/10
534/534 [==============================] - 0s 506us/step - loss: 0.4272 - accuracy: 0.7980
Epoch 4/10
534/534 [==============================] - 0s 491us/step - loss: 0.4236 - accuracy: 0.7999
Epoch 5/10
534/534 [==============================] - 0s 524us/step - loss: 0.4191 - accuracy: 0.8224
Epoch 6/10
534/534 [==============================] - 0s 532us/step - loss: 0.4153 - accuracy: 0.8281
Epoch 7/10
534/534 [==============================] - 0s 522us/step - loss: 0.4120 - accuracy: 0.8324
Epoch 8/10
534/534 [==============================] - 0s 524us/step - loss: 0.4099 - accuracy: 0.8339
Epoch 9/10
534/534 [==============================] - 0s 522us/step - loss: 0.4074 - accuracy: 0.8333
Epoch 10/10
534/534 [==============================] - 0s 510us/step - loss: 0.405

534/534 [==============================] - 0s 486us/step - loss: 0.3626 - accuracy: 0.8547
Epoch 1/20
534/534 [==============================] - 0s 512us/step - loss: 0.5174 - accuracy: 0.7934
Epoch 2/20
534/534 [==============================] - 0s 465us/step - loss: 0.4347 - accuracy: 0.7935
Epoch 3/20
534/534 [==============================] - 0s 480us/step - loss: 0.4289 - accuracy: 0.7935
Epoch 4/20
534/534 [==============================] - 0s 482us/step - loss: 0.4246 - accuracy: 0.7935
Epoch 5/20
534/534 [==============================] - 0s 484us/step - loss: 0.4211 - accuracy: 0.8020
Epoch 6/20
534/534 [==============================] - 0s 514us/step - loss: 0.4184 - accuracy: 0.8219
Epoch 7/20
534/534 [==============================] - 0s 594us/step - loss: 0.4170 - accuracy: 0.8234
Epoch 8/20
534/534 [==============================] - 0s 605us/step - loss: 0.4152 - accuracy: 0.8260
Epoch 9/20
534/534 [==============================] - 0s 543us/step - loss: 0.4142 - accuracy

534/534 [==============================] - 0s 515us/step - loss: 0.4095 - accuracy: 0.8341
Epoch 18/20
534/534 [==============================] - 0s 474us/step - loss: 0.4086 - accuracy: 0.8346
Epoch 19/20
534/534 [==============================] - 0s 498us/step - loss: 0.4081 - accuracy: 0.8348
Epoch 20/20
534/534 [==============================] - 0s 501us/step - loss: 0.4075 - accuracy: 0.8341
Epoch 1/20
534/534 [==============================] - 0s 532us/step - loss: 0.5443 - accuracy: 0.7957
Epoch 2/20
534/534 [==============================] - 0s 482us/step - loss: 0.4347 - accuracy: 0.7964
Epoch 3/20
534/534 [==============================] - 0s 501us/step - loss: 0.4280 - accuracy: 0.7964
Epoch 4/20
534/534 [==============================] - 0s 485us/step - loss: 0.4240 - accuracy: 0.7964
Epoch 5/20
534/534 [==============================] - 0s 486us/step - loss: 0.4204 - accuracy: 0.7964
Epoch 6/20
534/534 [==============================] - 0s 488us/step - loss: 0.4179 - accur

534/534 [==============================] - 0s 517us/step - loss: 0.4245 - accuracy: 0.7964
Epoch 5/10
534/534 [==============================] - 0s 466us/step - loss: 0.4209 - accuracy: 0.7964
Epoch 6/10
534/534 [==============================] - 0s 492us/step - loss: 0.4180 - accuracy: 0.8151
Epoch 7/10
534/534 [==============================] - 0s 463us/step - loss: 0.4159 - accuracy: 0.8286
Epoch 8/10
534/534 [==============================] - 0s 493us/step - loss: 0.4137 - accuracy: 0.8309
Epoch 9/10
534/534 [==============================] - 0s 502us/step - loss: 0.4127 - accuracy: 0.8328
Epoch 10/10
534/534 [==============================] - 0s 486us/step - loss: 0.4114 - accuracy: 0.8341
Epoch 1/20
534/534 [==============================] - 0s 527us/step - loss: 0.5223 - accuracy: 0.7965
Epoch 2/20
534/534 [==============================] - 0s 462us/step - loss: 0.4196 - accuracy: 0.8157
Epoch 3/20
534/534 [==============================] - 0s 505us/step - loss: 0.4065 - accurac

534/534 [==============================] - 0s 499us/step - loss: 0.3748 - accuracy: 0.8466
Epoch 12/20
534/534 [==============================] - 0s 515us/step - loss: 0.3723 - accuracy: 0.8483
Epoch 13/20
534/534 [==============================] - 0s 489us/step - loss: 0.3707 - accuracy: 0.8483
Epoch 14/20
534/534 [==============================] - 0s 521us/step - loss: 0.3683 - accuracy: 0.8504
Epoch 15/20
534/534 [==============================] - 0s 500us/step - loss: 0.3656 - accuracy: 0.8522
Epoch 16/20
534/534 [==============================] - 0s 508us/step - loss: 0.3663 - accuracy: 0.8521
Epoch 17/20
534/534 [==============================] - 0s 482us/step - loss: 0.3651 - accuracy: 0.8545
Epoch 18/20
534/534 [==============================] - 0s 495us/step - loss: 0.3638 - accuracy: 0.8522
Epoch 19/20
534/534 [==============================] - 0s 508us/step - loss: 0.3624 - accuracy: 0.8562
Epoch 20/20
534/534 [==============================] - 0s 491us/step - loss: 0.3617 -

In [35]:
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

In [36]:
print(best_parameters)
print(best_accuracy)

{'batch_size': 10, 'epochs': 20, 'optimizer': 'rmsprop'}
0.8491257610053058
